spring:
  datasource:
    url: jdbc:sqlserver://pfeskander.database.windows.net:1433;database=pfebd;user=skander@pfeskander;password=Sk20334951;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080


